version: "3.7"
name: app-backend
services:
## Contenedor para la base de datos 
  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: "app_db"
      MYSQL_ROOT_PASSWORD: "password_root"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "password_admin"
      SERVICE_TAGS: bd_app
      SERVICE_NAME: mysql
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - app-network

## Contenedor de la aplicacion del backend
  app:
    build:
      args:
        user: admin
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: app
    container_name: app
    depends_on:
      db:
        condition: service_started
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
      - ./log/codeigniter:/var/www/html/writable/logs
      - ./conf/php:/usr/local/etc/php
    networks:
      - app-network

## Contenedor para el servicio web del backend
  nginx:
    image: nginx:stable-alpine3.17
    container_name: web
    depends_on:
      app:
        condition: service_started
    restart: unless-stopped
    ports:
      - 8080:80
      # - 443:443
    volumes:
      - ./src:/var/www/html
      # - ./certificado:/etc/nginx/ssl
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./log/nginx:/var/log/nginx
    networks:
      - app-network

## Contenedor para crear los respaldos del backend
  periodic-backup:
    build:
      context: ./periodic-backup
    container_name: backups
    depends_on:
      db:
        condition: service_started
    restart: always
    environment:
      ## Nombre del contenedor de base de datos 
      MYSQL_CONTAINER_NAME: db
      ## Credenciales de conexion a base de datos para respaldo
      MYSQL_DATABASE: app_db
      MYSQL_ROOT_PASSWORD: "password_root"
    volumes:
      #- /etc/localtime:/etc/localtime:ro
      ## Rutas para guardar los respaldos del proyecto
      - ./backup/data-base:/opt/mysql/backup
      - ./backup/files:/home/backup/files
      - ./backup/config:/home/backup/config
      - ./backup/src:/home/backup/src
      ## Ruta de acceso a las carpetas y archivos del proyecto para respaldar
      - .:/home/app-backend
    command: crond -f -d 8
    networks:
      - app-network

## Contenedor para las tareas programadas del backend
  cron-jobs:
    build:
      context: ./cron-jobs
    container_name: cron-jobs
    depends_on:
      app:
        condition: service_started
    restart: always
    #volumes:
    ## Volumenes de las carpetas que se utilicen las tareas programadas
      #- /etc/localtime:/etc/localtime:ro
      #- ./src/files/temp:/home/app-backend/pdfsTemp
    command: crond -f -d 8
    networks:
      - app-network

## Red del backend
networks:
  app-network:
    driver: bridge
