version: "3.7"
services:
  builder:
    image: composer:latest
    container_name: builder-app
    volumes:
      - ./src:/app
    stdin_open: true
    tty: true
    command: require --ignore-platform-reqs codeigniter4/framework

  app:
    build:
      args:
        user: dev
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: app
    container_name: app
    depends_on:
      builder:
        condition: service_completed_successfully
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    networks:
      - desarrollo

  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: "app"
      MYSQL_ROOT_PASSWORD: "Rompevientos"
      MYSQL_USER: "desarrollo"
      MYSQL_PASSWORD: "Rompevientos"
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    networks:
      - desarrollo

  nginx:
    image: nginx
    container_name: web
    depends_on:
      app:
        condition: service_started
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - desarrollo
networks:
  desarrollo:
    driver: bridge
