version: "3.7"
name: backend
services:
  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: "app_db"
      MYSQL_ROOT_PASSWORD: "password_root"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "password_admin"
      SERVICE_TAGS: bd_app
      SERVICE_NAME: mysql
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - app-network

  app:
    build:
      args:
        user: admin
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: app
    container_name: app
    depends_on:
      db:
        condition: service_started
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
      - ./log/codeigniter:/var/www/html/writable/logs
    networks:
      - app-network

  nginx:
    image: nginx
    container_name: web
    depends_on:
      app:
        condition: service_started
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./log/nginx:/var/log/nginx
    networks:
      - app-network

  periodic-backup:
    build:
      context: ./periodic-backup
    container_name: backups
    depends_on:
      db:
        condition: service_started
    restart: always
    environment:
      MYSQL_CONTAINER_NAME: db
      MYSQL_DATABASE: app_db
      MYSQL_ROOT_PASSWORD: "password_root"
    volumes:
      #- /etc/localtime:/etc/localtime:ro
      - ./backup/data-base:/opt/mysql/backup
      - ./backup/files:/home/backup/files
      - ./backup/config:/home/backup/config
      - ./backup/src:/home/backup/src
      - .:/home/app-backend
    command: crond -f -d 8
    networks:
      - app-network

  cron-jobs:
    build:
      context: ./cron-jobs
    container_name: cron-jobs
    depends_on:
      app:
        condition: service_started
    restart: always
    #volumes:
      #- /etc/localtime:/etc/localtime:ro
      #- ./src/files/temp:/home/app-backend/pdfsTemp
    command: crond -f -d 8
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
