#!/bin/sh
echo "Deshabilitando Sitio de Archivo Historico del Consejo Academico UAM-X ..."
echo "Fecha y hora actual: $(date)"
DOCKER=$(which docker)

$DOCKER compose down

echo "El Sitio de Archivo Historico del Consejo Academico UAM-X se deshabilito exitosamente."
