#!/bin/sh
echo "Iniciando el script de respaldo CONFIGURACION de DOCKER..."
echo "Fecha y hora actual: $(date)"
BACKUP_FOLDER=/home/backup/config

DIR_FOLDER_CRON_JOBS=/home/app-backend/cron-jobs/
DIR_FOLDER_PERIODIC_BACKUP=/home/app-backend/periodic-backup/
FILE_DOCKER_BACKUP=/home/app-backend/Dockerfile
FILE_DOCKER_COMPOSE_BACKUP=/home/app-backend/docker-compose.yml
FILE_LOAD_BD_BACKUP=/home/app-backend/comand-for-load-db
#Script para linux
FILE_START_UP_BACKUP=/home/app-backend/start-up
FILE_START_DOWN_BACKUP=/home/app-backend/start-down
#Script para windows
FILE_START_WN_UP_BACKUP=/home/app-backend/wn-start-up.bat
FILE_START_WN_DOWN_BACKUP=/home/app-backend/wn-start-down.bat
FILE_START_WN_CONSOLE_APP_BACKUP=/home/app-backend/wn-console-app.bat
FILE_START_WN_BUILD_BACKUP=/home/app-backend/wn-build.bat

NOW=$(date '+%Y%m%d')
TAR=$(which tar)
[ ! -d "$BACKUP_FOLDER" ] && mkdir --parents $BACKUP_FOLDER
rm -r $BACKUP_FOLDER/backup-docker-conf-*.tar.gz
FILE=${BACKUP_FOLDER}/backup-docker-conf-${NOW}.tar.gz
$TAR -czvf ${FILE} ${DIR_FOLDER_CRON_JOBS} ${DIR_FOLDER_PERIODIC_BACKUP} ${FILE_DOCKER_BACKUP} ${FILE_DOCKER_COMPOSE_BACKUP} ${FILE_START_UP_BACKUP} ${FILE_START_DOWN_BACKUP} ${FILE_LOAD_BD_BACKUP} ${FILE_START_WN_BUILD_BACKUP} ${FILE_START_WN_CONSOLE_APP_BACKUP} ${FILE_START_WN_DOWN_BACKUP} ${FILE_START_WN_UP_BACKUP}
echo "Script de respaldo CONFIGURACION de DOCKER completado exitosamente."
