#!/bin/sh
echo "Iniciando el script de respaldo FILES..."
echo "Fecha y hora actual: $(date)"
BACKUP_FOLDER=/home/backup/files
DIR_FOLDER=/home/app-backend/files/
NOW=$(date '+%Y%m%d')
TAR=$(which tar)
[ ! -d "$BACKUP_FOLDER" ] && mkdir --parents $BACKUP_FOLDER
rm -r $BACKUP_FOLDER/*
FILE=${BACKUP_FOLDER}/backup-files-${NOW}.tar.gz
$TAR -czvf ${FILE} ${DIR_FOLDER} 
echo "Script de respaldo FILES completado exitosamente."
