#!/bin/sh
echo "Iniciando el script de respaldo CODIGO..."
echo "Fecha y hora actual: $(date)"
BACKUP_FOLDER=/home/backup/src
DIR_FOLDER=/home/app-backend/src/
NOW=$(date '+%Y%m%d')
TAR=$(which tar)
[ ! -d "$BACKUP_FOLDER" ] && mkdir --parents $BACKUP_FOLDER
rm -r $BACKUP_FOLDER/*
FILE=${BACKUP_FOLDER}/backup-src-${NOW}.tar.gz
$TAR -czvf ${FILE} ${DIR_FOLDER} 
echo "Script de respaldo CODIGO completado exitosamente."
